name: Swift App Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Accept Xcode License
      run: sudo xcodebuild -license accept

    - name: List Available Simulators
      run: xcrun simctl list

    - name: Clean Build Directory
      run: xcodebuild clean -scheme WeSplitApp

    - name: Build Swift App
      run: xcodebuild -scheme WeSplitApp -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' build

    - name: Run Unit Tests
      run: xcodebuild -scheme WeSplitApp -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' test
